local QuestConfig = {
	DAILY_BOARD_SIZE = 3,
	STARTER = {
		first_collect = {
			id = "first_collect",
			sortOrder = 1,
			category = "starter",
			name = "First Stack Of Hype",
			description = "Collect 12 total Hype.",
			type = "collect_hype",
			target = 12,
			reward = {
				currency = "hype",
				amount = 20,
			},
		},
		first_upgrade = {
			id = "first_upgrade",
			sortOrder = 2,
			category = "starter",
			name = "Tune The Board",
			description = "Buy your first upgrade.",
			type = "buy_upgrade",
			target = 1,
			reward = {
				currency = "hype",
				amount = 35,
			},
		},
		first_merge = {
			id = "first_merge",
			sortOrder = 3,
			category = "starter",
			name = "Make Your First Merge",
			description = "Merge a pair of matching stickers.",
			type = "merge_sticker",
			target = 1,
			reward = {
				currency = "hype",
				amount = 65,
			},
		},
		first_zone_unlock = {
			id = "first_zone_unlock",
			sortOrder = 4,
			category = "starter",
			name = "Open Neon Alley",
			description = "Unlock Neon Alley to widen your board.",
			type = "unlock_zone",
			target = 1,
			reward = {
				currency = "hype",
				amount = 150,
			},
		},
		first_reprint = {
			id = "first_reprint",
			sortOrder = 5,
			category = "starter",
			name = "Press The Reprint Button",
			description = "Complete your first Reprint for permanent Ink.",
			type = "reprint",
			target = 1,
			reward = {
				currency = "inkShards",
				amount = 1,
			},
		},
	},
	DAILY_TEMPLATES = {
		collect_burst = {
			id = "collect_burst",
			sortOrder = 1,
			category = "daily",
			name = "Street Sweep",
			description = "Collect 240 Hype today.",
			type = "collect_hype",
			target = 240,
			weight = 5,
			reward = {
				currency = "hype",
				amount = 110,
			},
			minimumZoneOrder = 1,
		},
		collect_push = {
			id = "collect_push",
			sortOrder = 2,
			category = "daily",
			name = "Prime The Press",
			description = "Collect 520 Hype today.",
			type = "collect_hype",
			target = 520,
			weight = 4,
			reward = {
				currency = "hype",
				amount = 220,
			},
			minimumLifetimeHype = 220,
		},
		upgrade_sprint = {
			id = "upgrade_sprint",
			sortOrder = 3,
			category = "daily",
			name = "Supply Run",
			description = "Buy 2 upgrades today.",
			type = "buy_upgrade",
			target = 2,
			weight = 4,
			reward = {
				currency = "hype",
				amount = 140,
			},
			minimumZoneOrder = 1,
		},
		upgrade_push = {
			id = "upgrade_push",
			sortOrder = 4,
			category = "daily",
			name = "Board Builder",
			description = "Buy 4 upgrades today.",
			type = "buy_upgrade",
			target = 4,
			weight = 3,
			reward = {
				currency = "hype",
				amount = 260,
			},
			minimumLifetimeHype = 380,
		},
		merge_pair = {
			id = "merge_pair",
			sortOrder = 5,
			category = "daily",
			name = "Foil Mixer",
			description = "Merge 2 sticker pairs today.",
			type = "merge_sticker",
			target = 2,
			weight = 4,
			reward = {
				currency = "hype",
				amount = 160,
			},
			minimumZoneOrder = 1,
		},
		merge_chain = {
			id = "merge_chain",
			sortOrder = 6,
			category = "daily",
			name = "Upgrade Cascade",
			description = "Merge 4 sticker pairs today.",
			type = "merge_sticker",
			target = 4,
			weight = 2,
			reward = {
				currency = "hype",
				amount = 320,
			},
			minimumZoneOrder = 2,
		},
		print_pair = {
			id = "print_pair",
			sortOrder = 7,
			category = "daily",
			name = "Sticker Restock",
			description = "Print 2 sticker copies today.",
			type = "print_sticker",
			target = 2,
			weight = 4,
			reward = {
				currency = "hype",
				amount = 140,
			},
			minimumZoneOrder = 1,
		},
		print_push = {
			id = "print_push",
			sortOrder = 8,
			category = "daily",
			name = "Printer Heat",
			description = "Print 5 sticker copies today.",
			type = "print_sticker",
			target = 5,
			weight = 3,
			reward = {
				currency = "hype",
				amount = 280,
			},
			minimumLifetimeHype = 180,
		},
		zone_spotlight = {
			id = "zone_spotlight",
			sortOrder = 9,
			category = "daily",
			name = "New Block",
			description = "Unlock a new zone today.",
			type = "unlock_zone",
			target = 1,
			weight = 1,
			reward = {
				currency = "hype",
				amount = 400,
			},
			minimumZoneOrder = 1,
			maximumZoneOrder = 1,
		},
		reprint_prep = {
			id = "reprint_prep",
			sortOrder = 10,
			category = "daily",
			name = "Fresh Plate",
			description = "Complete 1 Reprint today.",
			type = "reprint",
			target = 1,
			weight = 1,
			reward = {
				currency = "hype",
				amount = 600,
			},
			minimumLifetimeHype = 1400,
		},
	},
}

return QuestConfig
