local StickerConfig = {
	basic_smile = {
		id = "basic_smile",
		sortOrder = 1,
		familyId = "smile_line",
		zoneId = "sticker_street",
		tier = 1,
		printCost = 18,
		name = "Basic Smile",
		rarity = "Common",
		baseProduction = 1,
		mergeInto = "neon_cat",
		description = "The first sticker on every board.",
	},
	neon_cat = {
		id = "neon_cat",
		sortOrder = 2,
		familyId = "smile_line",
		zoneId = "sticker_street",
		tier = 2,
		name = "Neon Cat",
		rarity = "Uncommon",
		baseProduction = 4,
		mergeInto = "holo_dragon",
		description = "A bright sticker that hums with city energy.",
	},
	holo_dragon = {
		id = "holo_dragon",
		sortOrder = 3,
		familyId = "smile_line",
		zoneId = "sticker_street",
		tier = 3,
		name = "Holo Dragon",
		rarity = "Rare",
		baseProduction = 12,
		mergeInto = "cosmic_ghost",
		description = "Rare foil scales make this one a hype machine.",
	},
	cosmic_ghost = {
		id = "cosmic_ghost",
		sortOrder = 4,
		familyId = "smile_line",
		zoneId = "sticker_street",
		tier = 4,
		name = "Cosmic Ghost",
		rarity = "Epic",
		baseProduction = 36,
		mergeInto = nil,
		description = "A floating flex piece for late-alpha sessions.",
	},
	arcade_bunny = {
		id = "arcade_bunny",
		sortOrder = 5,
		familyId = "arcade_line",
		zoneId = "sticker_street",
		tier = 1,
		printCost = 70,
		name = "Arcade Bunny",
		rarity = "Common",
		baseProduction = 1.2000000477,
		mergeInto = "pixel_koala",
		description = "Unlocked by stretching the board into new lanes.",
	},
	pixel_koala = {
		id = "pixel_koala",
		sortOrder = 6,
		familyId = "arcade_line",
		zoneId = "sticker_street",
		tier = 2,
		name = "Pixel Koala",
		rarity = "Uncommon",
		baseProduction = 4.8000001907,
		mergeInto = "glitch_pigeon",
		description = "A soft glitch sticker that prints clean profits.",
	},
	glitch_pigeon = {
		id = "glitch_pigeon",
		sortOrder = 7,
		familyId = "arcade_line",
		zoneId = "sticker_street",
		tier = 3,
		name = "Glitch Pigeon",
		rarity = "Rare",
		baseProduction = 14.3999996185,
		mergeInto = "laser_pegasus",
		description = "A scrambled flyer that keeps the board noisy.",
	},
	laser_pegasus = {
		id = "laser_pegasus",
		sortOrder = 8,
		familyId = "arcade_line",
		zoneId = "sticker_street",
		tier = 4,
		name = "Laser Pegasus",
		rarity = "Epic",
		baseProduction = 43.2000007629,
		mergeInto = nil,
		description = "A rare arcade myth with a perfect foil shine.",
	},
	soda_slime = {
		id = "soda_slime",
		sortOrder = 9,
		familyId = "neon_line",
		zoneId = "neon_alley",
		tier = 1,
		printCost = 120,
		name = "Soda Slime",
		rarity = "Common",
		baseProduction = 1.5,
		mergeInto = "turbo_tiger",
		description = "Neon Alley's fizzy first recruit.",
	},
	turbo_tiger = {
		id = "turbo_tiger",
		sortOrder = 10,
		familyId = "neon_line",
		zoneId = "neon_alley",
		tier = 2,
		name = "Turbo Tiger",
		rarity = "Uncommon",
		baseProduction = 6,
		mergeInto = "disco_phoenix",
		description = "This alley cat sprints through every payout tick.",
	},
	disco_phoenix = {
		id = "disco_phoenix",
		sortOrder = 11,
		familyId = "neon_line",
		zoneId = "neon_alley",
		tier = 3,
		name = "Disco Phoenix",
		rarity = "Rare",
		baseProduction = 18,
		mergeInto = "billboard_titan",
		description = "A heatwave sticker that owns the skyline.",
	},
	billboard_titan = {
		id = "billboard_titan",
		sortOrder = 12,
		familyId = "neon_line",
		zoneId = "neon_alley",
		tier = 4,
		name = "Billboard Titan",
		rarity = "Epic",
		baseProduction = 54,
		mergeInto = nil,
		description = "A giant foil icon built for the brightest strip in town.",
	},
}

return StickerConfig
