local TutorialConfig = {
	ORDER = {
		"collect_once",
		"print_basic_smile",
		"merge_neon_cat",
		"buy_tap_power_lv1",
		"claim_any_quest",
		"unlock_neon_alley",
	},
	STEPS = {
		collect_once = {
			id = "collect_once",
			sortOrder = 1,
			name = "Kick Off The Board",
			description = "Tap the board once to start building Hype.",
			actionLabel = "Tap The Board",
			pageId = "play",
			targetType = "collectButton",
			targetId = nil,
		},
		print_basic_smile = {
			id = "print_basic_smile",
			sortOrder = 2,
			name = "Print A Second Smile",
			description = "Print one more Basic Smile so you can start merging.",
			actionLabel = "Print Basic Smile",
			pageId = "play",
			targetType = "printButton",
			targetId = "basic_smile",
		},
		merge_neon_cat = {
			id = "merge_neon_cat",
			sortOrder = 3,
			name = "Merge Into Neon Cat",
			description = "Combine two Basic Smiles into your first Neon Cat.",
			actionLabel = "Merge Stickers",
			pageId = "play",
			targetType = "mergeButton",
			targetId = "basic_smile",
		},
		buy_tap_power_lv1 = {
			id = "buy_tap_power_lv1",
			sortOrder = 4,
			name = "Buy Marker Mash",
			description = "Grab your first Tap upgrade so every collect hits harder.",
			actionLabel = "Buy Marker Mash",
			pageId = "play",
			targetType = "upgradeButton",
			targetId = "tap_power",
		},
		claim_any_quest = {
			id = "claim_any_quest",
			sortOrder = 5,
			name = "Claim A Reward",
			description = "Open the progress page and claim any finished quest.",
			actionLabel = "Claim Quest",
			pageId = "progress",
			targetType = "questButton",
			targetId = "any",
		},
		unlock_neon_alley = {
			id = "unlock_neon_alley",
			sortOrder = 6,
			name = "Reach Neon Alley",
			description = "Unlock Neon Alley to open the second real zone.",
			actionLabel = "Unlock Neon Alley",
			pageId = "play",
			targetType = "zoneButton",
			targetId = "neon_alley",
		},
	},
}

return TutorialConfig
