local UpgradeConfig = {
	tap_power = {
		id = "tap_power",
		sortOrder = 1,
		autoBuyPriority = 1,
		name = "Marker Mash",
		description = "Increase Hype earned from every manual collect.",
		currency = "hype",
		baseCost = 12,
		costGrowth = 1.65,
		maxLevel = 12,
		type = "standard",
	},
	sticker_printer = {
		id = "sticker_printer",
		sortOrder = 2,
		autoBuyPriority = 2,
		name = "Sticker Printer",
		description = "Boost sticker production across every family.",
		currency = "hype",
		baseCost = 28,
		costGrowth = 1.8500000477,
		maxLevel = 10,
		type = "standard",
	},
	auto_collector = {
		id = "auto_collector",
		sortOrder = 3,
		autoBuyPriority = 3,
		name = "Auto Collector",
		description = "Unlock automatic collection every second and scale it with level.",
		currency = "hype",
		baseCost = 60,
		costGrowth = 2.0499999523,
		maxLevel = 4,
		type = "standard",
	},
	merge_mastery = {
		id = "merge_mastery",
		sortOrder = 4,
		autoBuyPriority = 4,
		name = "Merge Mastery",
		description = "Boost production from every merged sticker tier.",
		currency = "hype",
		baseCost = 110,
		costGrowth = 1.9800000191,
		maxLevel = 6,
		type = "standard",
	},
	board_expander = {
		id = "board_expander",
		sortOrder = 5,
		autoBuyPriority = 5,
		name = "Board Expander",
		description = "Unlock a second family at level 1 and Auto Buy at level 2.",
		currency = "hype",
		baseCost = 170,
		costGrowth = 2,
		maxLevel = 4,
		type = "standard",
		unlocksSettings = {
			autoBuy = 2,
		},
		unlockRewards = {
			{
				level = 1,
				stickerId = "arcade_bunny",
				amount = 1,
			},
		},
	},
	auto_merge_unlock = {
		id = "auto_merge_unlock",
		sortOrder = 6,
		autoBuyPriority = 6,
		name = "Auto Merge",
		description = "Unlock hands-free merging for every owned family.",
		currency = "hype",
		baseCost = 220,
		costGrowth = 2.25,
		maxLevel = 1,
		type = "standard",
		unlocksSettings = {
			autoMerge = 1,
		},
	},
}

return UpgradeConfig
